name: aestesis_engine
description: "Aestesis Engine."
version: 1.0.5
repository: https://github.com/aestesis/aestesis_engine
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  collection: any
  uuid: any
  bb_dart:
    git: https://github.com/aestesis/bb.dart.git
  bb.flutter:
    git: https://github.com/aestesis/bb.flutter.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: any

flutter:
  config:
    enable-swift-package-manager: true
  plugin:
    platforms:
      ios:
        pluginClass: AestesisEnginePlugin
        sharedDarwinSource: true
      macos:
        pluginClass: AestesisEnginePlugin
        sharedDarwinSource: true

