// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum ControlType {
  float,
  unit,
  integer,
  boolean,
  color,
}

enum AnalogControl {
  zoom,
  blur,
  hue,
  saturation,
  brightness,
  white,
}

enum AnalogSourceControl {
  opacity,
  color,
  blendMode,
  gain,
}

enum CameraControl {
  asset,
}

enum FxControl {
  asset,
  level,
}

enum LutControl {
  asset,
  fade,
  intensity,
}

enum PlayerControl {
  asset,
  position,
}

enum ShaderControl {
  asset,
}

enum SynControl {
  asset,
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// //////////////////////////////////////////////////////////////////////////////////////////////////////
enum ControlBlendMode {
  normal,
  add,
  subtract,
  multiply,
  difference,
  exclusion,
  negation,
  luma,
  lumaAdd,
  lumaSubtract,
  lumaMultiply,
  screen,
  overlay,
  darken,
  lighten,
  colorDodge,
  colorBurn,
  hardLight,
  softLight,
  linearLight,
  linearBurn,
  glow,
  phoenix,
  reflect,
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum ModuleType {
  analog,
  camera,
  fx,
  lut,
  player,
  shader,
  syn,
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum CameraPosition {
  undefined,
  front,
  back,
  virtual,
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
enum CameraType {
  undefined,
  builtin,
  deskview,
  continuity,
  external,
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum MessageLevel {
  info,
  warning,
  error,
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
class Preview {
  Preview({
    required this.moduleId,
    this.assetId,
    required this.width,
    required this.height,
    required this.data,
  });

  String moduleId;

  String? assetId;

  int width;

  int height;

  Uint8List data;

  List<Object?> _toList() {
    return <Object?>[
      moduleId,
      assetId,
      width,
      height,
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static Preview decode(Object result) {
    result as List<Object?>;
    return Preview(
      moduleId: result[0]! as String,
      assetId: result[1] as String?,
      width: result[2]! as int,
      height: result[3]! as int,
      data: result[4]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Preview || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(moduleId, other.moduleId) && _deepEquals(assetId, other.assetId) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(data, other.data);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// //////////////////////////////////////////////////////////////////////////////////////////////////////
class AudioLevel {
  AudioLevel({
    required this.peak,
    required this.eq,
  });

  double peak;

  Equalizer eq;

  List<Object?> _toList() {
    return <Object?>[
      peak,
      eq,
    ];
  }

  Object encode() {
    return _toList();  }

  static AudioLevel decode(Object result) {
    result as List<Object?>;
    return AudioLevel(
      peak: result[0]! as double,
      eq: result[1]! as Equalizer,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioLevel || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(peak, other.peak) && _deepEquals(eq, other.eq);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////
class Equalizer {
  Equalizer({
    required this.low,
    required this.mid,
    required this.high,
  });

  double low;

  double mid;

  double high;

  List<Object?> _toList() {
    return <Object?>[
      low,
      mid,
      high,
    ];
  }

  Object encode() {
    return _toList();  }

  static Equalizer decode(Object result) {
    result as List<Object?>;
    return Equalizer(
      low: result[0]! as double,
      mid: result[1]! as double,
      high: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Equalizer || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(low, other.low) && _deepEquals(mid, other.mid) && _deepEquals(high, other.high);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
class Asset {
  Asset({
    required this.id,
    required this.name,
    this.uri,
  });

  String id;

  String name;

  String? uri;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      uri,
    ];
  }

  Object encode() {
    return _toList();  }

  static Asset decode(Object result) {
    result as List<Object?>;
    return Asset(
      id: result[0]! as String,
      name: result[1]! as String,
      uri: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Asset || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(uri, other.uri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
class Control {
  Control({
    required this.moduleId,
    required this.id,
    required this.type,
    required this.name,
    required this.value,
    required this.count,
  });

  String moduleId;

  String id;

  ControlType type;

  String name;

  double value;

  int count;

  List<Object?> _toList() {
    return <Object?>[
      moduleId,
      id,
      type,
      name,
      value,
      count,
    ];
  }

  Object encode() {
    return _toList();  }

  static Control decode(Object result) {
    result as List<Object?>;
    return Control(
      moduleId: result[0]! as String,
      id: result[1]! as String,
      type: result[2]! as ControlType,
      name: result[3]! as String,
      value: result[4]! as double,
      count: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Control || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(moduleId, other.moduleId) && _deepEquals(id, other.id) && _deepEquals(type, other.type) && _deepEquals(name, other.name) && _deepEquals(value, other.value) && _deepEquals(count, other.count);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
class Composition {
  Composition({
    required this.id,
    required this.name,
    required this.modules,
  });

  String id;

  String name;

  List<Module?> modules;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      modules,
    ];
  }

  Object encode() {
    return _toList();  }

  static Composition decode(Object result) {
    result as List<Object?>;
    return Composition(
      id: result[0]! as String,
      name: result[1]! as String,
      modules: (result[2]! as List<Object?>).cast<Module?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Composition || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(modules, other.modules);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
class Module {
  Module({
    required this.id,
    required this.type,
    required this.name,
    this.controls,
    this.assets,
  });

  String id;

  ModuleType type;

  String name;

  List<Control?>? controls;

  List<Asset?>? assets;

  List<Object?> _toList() {
    return <Object?>[
      id,
      type,
      name,
      controls,
      assets,
    ];
  }

  Object encode() {
    return _toList();  }

  static Module decode(Object result) {
    result as List<Object?>;
    return Module(
      id: result[0]! as String,
      type: result[1]! as ModuleType,
      name: result[2]! as String,
      controls: (result[3] as List<Object?>?)?.cast<Control?>(),
      assets: (result[4] as List<Object?>?)?.cast<Asset?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Module || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(type, other.type) && _deepEquals(name, other.name) && _deepEquals(controls, other.controls) && _deepEquals(assets, other.assets);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
class CameraDevice {
  CameraDevice({
    required this.id,
    required this.name,
    required this.model,
    required this.manufacturer,
    required this.position,
    required this.type,
  });

  String id;

  String name;

  String model;

  String manufacturer;

  CameraPosition position;

  CameraType type;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      model,
      manufacturer,
      position,
      type,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraDevice decode(Object result) {
    result as List<Object?>;
    return CameraDevice(
      id: result[0]! as String,
      name: result[1]! as String,
      model: result[2]! as String,
      manufacturer: result[3]! as String,
      position: result[4]! as CameraPosition,
      type: result[5]! as CameraType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(model, other.model) && _deepEquals(manufacturer, other.manufacturer) && _deepEquals(position, other.position) && _deepEquals(type, other.type);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// //////////////////////////////////////////////////////////////////////////////////////////////////////
class AudioDevice {
  AudioDevice({
    required this.id,
    required this.name,
    required this.manufacturer,
    required this.inputChannels,
    required this.outputChannels,
  });

  int id;

  String name;

  String manufacturer;

  List<String?> inputChannels;

  List<String?> outputChannels;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      manufacturer,
      inputChannels,
      outputChannels,
    ];
  }

  Object encode() {
    return _toList();  }

  static AudioDevice decode(Object result) {
    result as List<Object?>;
    return AudioDevice(
      id: result[0]! as int,
      name: result[1]! as String,
      manufacturer: result[2]! as String,
      inputChannels: (result[3]! as List<Object?>).cast<String?>(),
      outputChannels: (result[4]! as List<Object?>).cast<String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(manufacturer, other.manufacturer) && _deepEquals(inputChannels, other.inputChannels) && _deepEquals(outputChannels, other.outputChannels);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// /////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
class AudioSettings {
  AudioSettings({
    required this.deviceName,
    required this.leftChannel,
    required this.rightChannel,
  });

  String deviceName;

  int leftChannel;

  int rightChannel;

  List<Object?> _toList() {
    return <Object?>[
      deviceName,
      leftChannel,
      rightChannel,
    ];
  }

  Object encode() {
    return _toList();  }

  static AudioSettings decode(Object result) {
    result as List<Object?>;
    return AudioSettings(
      deviceName: result[0]! as String,
      leftChannel: result[1]! as int,
      rightChannel: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceName, other.deviceName) && _deepEquals(leftChannel, other.leftChannel) && _deepEquals(rightChannel, other.rightChannel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
class CompositionSettings {
  CompositionSettings({
    required this.width,
    required this.height,
    required this.fps,
    this.audioSettings,
  });

  double width;

  double height;

  double fps;

  AudioSettings? audioSettings;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      fps,
      audioSettings,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompositionSettings decode(Object result) {
    result as List<Object?>;
    return CompositionSettings(
      width: result[0]! as double,
      height: result[1]! as double,
      fps: result[2]! as double,
      audioSettings: result[3] as AudioSettings?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompositionSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(fps, other.fps) && _deepEquals(audioSettings, other.audioSettings);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
class CompositionStatistics {
  CompositionStatistics({
    required this.fps,
    required this.cpu,
    required this.gpu,
    required this.ram,
  });

  double fps;

  double cpu;

  double gpu;

  double ram;

  List<Object?> _toList() {
    return <Object?>[
      fps,
      cpu,
      gpu,
      ram,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompositionStatistics decode(Object result) {
    result as List<Object?>;
    return CompositionStatistics(
      fps: result[0]! as double,
      cpu: result[1]! as double,
      gpu: result[2]! as double,
      ram: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompositionStatistics || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fps, other.fps) && _deepEquals(cpu, other.cpu) && _deepEquals(gpu, other.gpu) && _deepEquals(ram, other.ram);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
class CompositionStates {
  CompositionStates({
    required this.recording,
    required this.streaming,
    required this.previewing,
  });

  bool recording;

  bool streaming;

  bool previewing;

  List<Object?> _toList() {
    return <Object?>[
      recording,
      streaming,
      previewing,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompositionStates decode(Object result) {
    result as List<Object?>;
    return CompositionStates(
      recording: result[0]! as bool,
      streaming: result[1]! as bool,
      previewing: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompositionStates || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(recording, other.recording) && _deepEquals(streaming, other.streaming) && _deepEquals(previewing, other.previewing);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
class AssetTexture {
  AssetTexture({
    required this.moduleId,
    required this.assetId,
    required this.textureId,
  });

  String moduleId;

  String assetId;

  int textureId;

  List<Object?> _toList() {
    return <Object?>[
      moduleId,
      assetId,
      textureId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AssetTexture decode(Object result) {
    result as List<Object?>;
    return AssetTexture(
      moduleId: result[0]! as String,
      assetId: result[1]! as String,
      textureId: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AssetTexture || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(moduleId, other.moduleId) && _deepEquals(assetId, other.assetId) && _deepEquals(textureId, other.textureId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ControlType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AnalogControl) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AnalogSourceControl) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is CameraControl) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is FxControl) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is LutControl) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is PlayerControl) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is ShaderControl) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is SynControl) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is ControlBlendMode) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is ModuleType) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    }    else if (value is CameraPosition) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    }    else if (value is CameraType) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    }    else if (value is MessageLevel) {
      buffer.putUint8(142);
      writeValue(buffer, value.index);
    }    else if (value is Preview) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is AudioLevel) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is Equalizer) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is Asset) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is Control) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is Composition) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is Module) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is CameraDevice) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is AudioDevice) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is AudioSettings) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    }    else if (value is CompositionSettings) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    }    else if (value is CompositionStatistics) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    }    else if (value is CompositionStates) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    }    else if (value is AssetTexture) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ControlType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AnalogControl.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AnalogSourceControl.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : CameraControl.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : FxControl.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : LutControl.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlayerControl.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : ShaderControl.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : SynControl.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : ControlBlendMode.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : ModuleType.values[value];
      case 140:
        final value = readValue(buffer) as int?;
        return value == null ? null : CameraPosition.values[value];
      case 141:
        final value = readValue(buffer) as int?;
        return value == null ? null : CameraType.values[value];
      case 142:
        final value = readValue(buffer) as int?;
        return value == null ? null : MessageLevel.values[value];
      case 143:
        return Preview.decode(readValue(buffer)!);
      case 144:
        return AudioLevel.decode(readValue(buffer)!);
      case 145:
        return Equalizer.decode(readValue(buffer)!);
      case 146:
        return Asset.decode(readValue(buffer)!);
      case 147:
        return Control.decode(readValue(buffer)!);
      case 148:
        return Composition.decode(readValue(buffer)!);
      case 149:
        return Module.decode(readValue(buffer)!);
      case 150:
        return CameraDevice.decode(readValue(buffer)!);
      case 151:
        return AudioDevice.decode(readValue(buffer)!);
      case 152:
        return AudioSettings.decode(readValue(buffer)!);
      case 153:
        return CompositionSettings.decode(readValue(buffer)!);
      case 154:
        return CompositionStatistics.decode(readValue(buffer)!);
      case 155:
        return CompositionStates.decode(readValue(buffer)!);
      case 156:
        return AssetTexture.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// /////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
class AestesisEngineApi {
  /// Constructor for [AestesisEngineApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AestesisEngineApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<Composition> newComposition() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.newComposition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<Composition> composition() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.composition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<Composition> updateComposition(Composition composition) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.updateComposition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[composition]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<CompositionSettings> settings(CompositionSettings? settings) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.settings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[settings]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CompositionSettings;
  }

  Future<Composition> updateModule(Module module) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.updateModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[module]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<Composition> addModule(Module module) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.addModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[module]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<Composition> insertModule(Module module, int index) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.insertModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[module, index]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<Composition> removeModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.removeModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<Composition> addAssets(String moduleId, List<Asset?> assets) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.addAssets$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId, assets]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<Composition> removeAssets(String moduleId, List<String?> assetIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.removeAssets$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId, assetIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Composition;
  }

  Future<void> updateControl(Control control) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.updateControl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[control]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> outputView(bool show) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.outputView$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[show]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startRecording(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.startRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopRecording() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.stopRecording$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<CameraDevice>> cameraDevices() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.cameraDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CameraDevice>();
  }

  Future<List<AudioDevice>> audioDevices() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.audioDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<AudioDevice>();
  }

  Future<List<String>> pickFiles(String title, String? directory, bool multiple, List<String> extensions) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.pickFiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[title, directory, multiple, extensions]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<void> setAssetData(String key, String json) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.setAssetData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[key, json]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<String?> getAssetData(String key) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.getAssetData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[key]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<void> setAssetDatas(String json) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.setAssetDatas$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[json]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<String?> getAssetDatas() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.getAssetDatas$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
abstract class MessageAestesisEngineApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void texture(AssetTexture asset);

  void message(MessageLevel level, String message);

  void preview(Preview preview);

  void statistics(CompositionStatistics statistics);

  void control(Control control);

  void audio(AudioLevel level);

  void states(CompositionStates states);

  static void setUp(MessageAestesisEngineApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.texture$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AssetTexture arg_asset = args[0]! as AssetTexture;
          try {
            api.texture(arg_asset);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.message$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final MessageLevel arg_level = args[0]! as MessageLevel;
          final String arg_message = args[1]! as String;
          try {
            api.message(arg_level, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.preview$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final Preview arg_preview = args[0]! as Preview;
          try {
            api.preview(arg_preview);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.statistics$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CompositionStatistics arg_statistics = args[0]! as CompositionStatistics;
          try {
            api.statistics(arg_statistics);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.control$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final Control arg_control = args[0]! as Control;
          try {
            api.control(arg_control);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.audio$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AudioLevel arg_level = args[0]! as AudioLevel;
          try {
            api.audio(arg_level);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.states$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CompositionStates arg_states = args[0]! as CompositionStates;
          try {
            api.states(arg_states);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
