// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum messagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum ControlType: Int, CaseIterable {
  case float = 0
  case unit = 1
  case integer = 2
  case boolean = 3
  case color = 4
}

enum AnalogControl: Int, CaseIterable {
  case zoom = 0
  case blur = 1
  case hue = 2
  case saturation = 3
  case brightness = 4
  case white = 5
}

enum AnalogSourceControl: Int, CaseIterable {
  case opacity = 0
  case color = 1
  case blendMode = 2
  case gain = 3
}

enum CameraControl: Int, CaseIterable {
  case asset = 0
}

enum FxControl: Int, CaseIterable {
  case asset = 0
  case level = 1
}

enum LutControl: Int, CaseIterable {
  case asset = 0
  case fade = 1
  case intensity = 2
}

enum PlayerControl: Int, CaseIterable {
  case asset = 0
  case position = 1
}

enum ShaderControl: Int, CaseIterable {
  case asset = 0
}

enum SynControl: Int, CaseIterable {
  case asset = 0
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// //////////////////////////////////////////////////////////////////////////////////////////////////////
enum ControlBlendMode: Int, CaseIterable {
  case normal = 0
  case add = 1
  case subtract = 2
  case multiply = 3
  case difference = 4
  case exclusion = 5
  case negation = 6
  case luma = 7
  case lumaAdd = 8
  case lumaSubtract = 9
  case lumaMultiply = 10
  case screen = 11
  case overlay = 12
  case darken = 13
  case lighten = 14
  case colorDodge = 15
  case colorBurn = 16
  case hardLight = 17
  case softLight = 18
  case linearLight = 19
  case linearBurn = 20
  case glow = 21
  case phoenix = 22
  case reflect = 23
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum ModuleType: Int, CaseIterable {
  case analog = 0
  case camera = 1
  case fx = 2
  case lutein = 3
  case player = 4
  case shader = 5
  case syn = 6
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum CameraPosition: Int, CaseIterable {
  case undefined = 0
  case front = 1
  case back = 2
  case virtual = 3
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
enum CameraType: Int, CaseIterable {
  case undefined = 0
  case builtin = 1
  case deskview = 2
  case continuity = 3
  case external = 4
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum MessageLevel: Int, CaseIterable {
  case info = 0
  case warning = 1
  case error = 2
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct Preview: Hashable, CustomStringConvertible {
  var moduleId: String
  var assetId: String? = nil
  var width: Int64
  var height: Int64
  var data: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Preview? {
    let moduleId = pigeonVar_list[0] as! String
    let assetId: String? = nilOrValue(pigeonVar_list[1])
    let width = pigeonVar_list[2] as! Int64
    let height = pigeonVar_list[3] as! Int64
    let data = pigeonVar_list[4] as! FlutterStandardTypedData

    return Preview(
      moduleId: moduleId,
      assetId: assetId,
      width: width,
      height: height,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      moduleId,
      assetId,
      width,
      height,
      data,
    ]
  }
  static func == (lhs: Preview, rhs: Preview) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.moduleId, rhs.moduleId) && messagesPigeonInternal.deepEquals(lhs.assetId, rhs.assetId) && messagesPigeonInternal.deepEquals(lhs.width, rhs.width) && messagesPigeonInternal.deepEquals(lhs.height, rhs.height) && messagesPigeonInternal.deepEquals(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Preview")
    messagesPigeonInternal.deepHash(value: moduleId, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: assetId, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: data, hasher: &hasher)
  }

  public var description: String {
    return "Preview(moduleId: \(String(describing: moduleId)), assetId: \(String(describing: assetId)), width: \(String(describing: width)), height: \(String(describing: height)), data: \(String(describing: data)))"
  }
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// //////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioLevel: Hashable, CustomStringConvertible {
  var peak: Double
  var eq: Equalizer


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioLevel? {
    let peak = pigeonVar_list[0] as! Double
    let eq = pigeonVar_list[1] as! Equalizer

    return AudioLevel(
      peak: peak,
      eq: eq
    )
  }
  func toList() -> [Any?] {
    return [
      peak,
      eq,
    ]
  }
  static func == (lhs: AudioLevel, rhs: AudioLevel) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.peak, rhs.peak) && messagesPigeonInternal.deepEquals(lhs.eq, rhs.eq)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioLevel")
    messagesPigeonInternal.deepHash(value: peak, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: eq, hasher: &hasher)
  }

  public var description: String {
    return "AudioLevel(peak: \(String(describing: peak)), eq: \(String(describing: eq)))"
  }
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct Equalizer: Hashable, CustomStringConvertible {
  var low: Double
  var mid: Double
  var high: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Equalizer? {
    let low = pigeonVar_list[0] as! Double
    let mid = pigeonVar_list[1] as! Double
    let high = pigeonVar_list[2] as! Double

    return Equalizer(
      low: low,
      mid: mid,
      high: high
    )
  }
  func toList() -> [Any?] {
    return [
      low,
      mid,
      high,
    ]
  }
  static func == (lhs: Equalizer, rhs: Equalizer) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.low, rhs.low) && messagesPigeonInternal.deepEquals(lhs.mid, rhs.mid) && messagesPigeonInternal.deepEquals(lhs.high, rhs.high)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Equalizer")
    messagesPigeonInternal.deepHash(value: low, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: mid, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: high, hasher: &hasher)
  }

  public var description: String {
    return "Equalizer(low: \(String(describing: low)), mid: \(String(describing: mid)), high: \(String(describing: high)))"
  }
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct Asset: Hashable, CustomStringConvertible {
  var id: String
  var name: String
  var uri: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Asset? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let uri: String? = nilOrValue(pigeonVar_list[2])

    return Asset(
      id: id,
      name: name,
      uri: uri
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      uri,
    ]
  }
  static func == (lhs: Asset, rhs: Asset) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.name, rhs.name) && messagesPigeonInternal.deepEquals(lhs.uri, rhs.uri)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Asset")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
  }

  public var description: String {
    return "Asset(id: \(String(describing: id)), name: \(String(describing: name)), uri: \(String(describing: uri)))"
  }
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct Control: Hashable, CustomStringConvertible {
  var moduleId: String
  var id: String
  var type: ControlType
  var name: String
  var value: Double
  var count: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Control? {
    let moduleId = pigeonVar_list[0] as! String
    let id = pigeonVar_list[1] as! String
    let type = pigeonVar_list[2] as! ControlType
    let name = pigeonVar_list[3] as! String
    let value = pigeonVar_list[4] as! Double
    let count = pigeonVar_list[5] as! Int64

    return Control(
      moduleId: moduleId,
      id: id,
      type: type,
      name: name,
      value: value,
      count: count
    )
  }
  func toList() -> [Any?] {
    return [
      moduleId,
      id,
      type,
      name,
      value,
      count,
    ]
  }
  static func == (lhs: Control, rhs: Control) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.moduleId, rhs.moduleId) && messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.type, rhs.type) && messagesPigeonInternal.deepEquals(lhs.name, rhs.name) && messagesPigeonInternal.deepEquals(lhs.value, rhs.value) && messagesPigeonInternal.deepEquals(lhs.count, rhs.count)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Control")
    messagesPigeonInternal.deepHash(value: moduleId, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: value, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: count, hasher: &hasher)
  }

  public var description: String {
    return "Control(moduleId: \(String(describing: moduleId)), id: \(String(describing: id)), type: \(String(describing: type)), name: \(String(describing: name)), value: \(String(describing: value)), count: \(String(describing: count)))"
  }
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct Composition: Hashable, CustomStringConvertible {
  var id: String
  var name: String
  var modules: [Module?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Composition? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let modules = pigeonVar_list[2] as! [Module?]

    return Composition(
      id: id,
      name: name,
      modules: modules
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      modules,
    ]
  }
  static func == (lhs: Composition, rhs: Composition) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.name, rhs.name) && messagesPigeonInternal.deepEquals(lhs.modules, rhs.modules)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Composition")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: modules, hasher: &hasher)
  }

  public var description: String {
    return "Composition(id: \(String(describing: id)), name: \(String(describing: name)), modules: \(String(describing: modules)))"
  }
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct Module: Hashable, CustomStringConvertible {
  var id: String
  var type: ModuleType
  var name: String
  var controls: [Control?]? = nil
  var assets: [Asset?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Module? {
    let id = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! ModuleType
    let name = pigeonVar_list[2] as! String
    let controls: [Control?]? = nilOrValue(pigeonVar_list[3])
    let assets: [Asset?]? = nilOrValue(pigeonVar_list[4])

    return Module(
      id: id,
      type: type,
      name: name,
      controls: controls,
      assets: assets
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      name,
      controls,
      assets,
    ]
  }
  static func == (lhs: Module, rhs: Module) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.type, rhs.type) && messagesPigeonInternal.deepEquals(lhs.name, rhs.name) && messagesPigeonInternal.deepEquals(lhs.controls, rhs.controls) && messagesPigeonInternal.deepEquals(lhs.assets, rhs.assets)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Module")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: controls, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: assets, hasher: &hasher)
  }

  public var description: String {
    return "Module(id: \(String(describing: id)), type: \(String(describing: type)), name: \(String(describing: name)), controls: \(String(describing: controls)), assets: \(String(describing: assets)))"
  }
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct CameraDevice: Hashable, CustomStringConvertible {
  var id: String
  var name: String
  var model: String
  var manufacturer: String
  var position: CameraPosition
  var type: CameraType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CameraDevice? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let model = pigeonVar_list[2] as! String
    let manufacturer = pigeonVar_list[3] as! String
    let position = pigeonVar_list[4] as! CameraPosition
    let type = pigeonVar_list[5] as! CameraType

    return CameraDevice(
      id: id,
      name: name,
      model: model,
      manufacturer: manufacturer,
      position: position,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      model,
      manufacturer,
      position,
      type,
    ]
  }
  static func == (lhs: CameraDevice, rhs: CameraDevice) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.name, rhs.name) && messagesPigeonInternal.deepEquals(lhs.model, rhs.model) && messagesPigeonInternal.deepEquals(lhs.manufacturer, rhs.manufacturer) && messagesPigeonInternal.deepEquals(lhs.position, rhs.position) && messagesPigeonInternal.deepEquals(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CameraDevice")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: manufacturer, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: position, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: type, hasher: &hasher)
  }

  public var description: String {
    return "CameraDevice(id: \(String(describing: id)), name: \(String(describing: name)), model: \(String(describing: model)), manufacturer: \(String(describing: manufacturer)), position: \(String(describing: position)), type: \(String(describing: type)))"
  }
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// //////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioDevice: Hashable, CustomStringConvertible {
  var id: Int64
  var name: String
  var manufacturer: String
  var inputChannels: [String?]
  var outputChannels: [String?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioDevice? {
    let id = pigeonVar_list[0] as! Int64
    let name = pigeonVar_list[1] as! String
    let manufacturer = pigeonVar_list[2] as! String
    let inputChannels = pigeonVar_list[3] as! [String?]
    let outputChannels = pigeonVar_list[4] as! [String?]

    return AudioDevice(
      id: id,
      name: name,
      manufacturer: manufacturer,
      inputChannels: inputChannels,
      outputChannels: outputChannels
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      manufacturer,
      inputChannels,
      outputChannels,
    ]
  }
  static func == (lhs: AudioDevice, rhs: AudioDevice) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.id, rhs.id) && messagesPigeonInternal.deepEquals(lhs.name, rhs.name) && messagesPigeonInternal.deepEquals(lhs.manufacturer, rhs.manufacturer) && messagesPigeonInternal.deepEquals(lhs.inputChannels, rhs.inputChannels) && messagesPigeonInternal.deepEquals(lhs.outputChannels, rhs.outputChannels)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioDevice")
    messagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: manufacturer, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: inputChannels, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: outputChannels, hasher: &hasher)
  }

  public var description: String {
    return "AudioDevice(id: \(String(describing: id)), name: \(String(describing: name)), manufacturer: \(String(describing: manufacturer)), inputChannels: \(String(describing: inputChannels)), outputChannels: \(String(describing: outputChannels)))"
  }
}

/// /////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioSettings: Hashable, CustomStringConvertible {
  var deviceName: String
  var leftChannel: Int64
  var rightChannel: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioSettings? {
    let deviceName = pigeonVar_list[0] as! String
    let leftChannel = pigeonVar_list[1] as! Int64
    let rightChannel = pigeonVar_list[2] as! Int64

    return AudioSettings(
      deviceName: deviceName,
      leftChannel: leftChannel,
      rightChannel: rightChannel
    )
  }
  func toList() -> [Any?] {
    return [
      deviceName,
      leftChannel,
      rightChannel,
    ]
  }
  static func == (lhs: AudioSettings, rhs: AudioSettings) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.deviceName, rhs.deviceName) && messagesPigeonInternal.deepEquals(lhs.leftChannel, rhs.leftChannel) && messagesPigeonInternal.deepEquals(lhs.rightChannel, rhs.rightChannel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioSettings")
    messagesPigeonInternal.deepHash(value: deviceName, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: leftChannel, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: rightChannel, hasher: &hasher)
  }

  public var description: String {
    return "AudioSettings(deviceName: \(String(describing: deviceName)), leftChannel: \(String(describing: leftChannel)), rightChannel: \(String(describing: rightChannel)))"
  }
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct CompositionSettings: Hashable, CustomStringConvertible {
  var width: Double
  var height: Double
  var fps: Double
  var audioSettings: AudioSettings? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompositionSettings? {
    let width = pigeonVar_list[0] as! Double
    let height = pigeonVar_list[1] as! Double
    let fps = pigeonVar_list[2] as! Double
    let audioSettings: AudioSettings? = nilOrValue(pigeonVar_list[3])

    return CompositionSettings(
      width: width,
      height: height,
      fps: fps,
      audioSettings: audioSettings
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      fps,
      audioSettings,
    ]
  }
  static func == (lhs: CompositionSettings, rhs: CompositionSettings) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.width, rhs.width) && messagesPigeonInternal.deepEquals(lhs.height, rhs.height) && messagesPigeonInternal.deepEquals(lhs.fps, rhs.fps) && messagesPigeonInternal.deepEquals(lhs.audioSettings, rhs.audioSettings)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompositionSettings")
    messagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: fps, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: audioSettings, hasher: &hasher)
  }

  public var description: String {
    return "CompositionSettings(width: \(String(describing: width)), height: \(String(describing: height)), fps: \(String(describing: fps)), audioSettings: \(String(describing: audioSettings)))"
  }
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct CompositionStatistics: Hashable, CustomStringConvertible {
  var fps: Double
  var cpu: Double
  var gpu: Double
  var ram: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompositionStatistics? {
    let fps = pigeonVar_list[0] as! Double
    let cpu = pigeonVar_list[1] as! Double
    let gpu = pigeonVar_list[2] as! Double
    let ram = pigeonVar_list[3] as! Double

    return CompositionStatistics(
      fps: fps,
      cpu: cpu,
      gpu: gpu,
      ram: ram
    )
  }
  func toList() -> [Any?] {
    return [
      fps,
      cpu,
      gpu,
      ram,
    ]
  }
  static func == (lhs: CompositionStatistics, rhs: CompositionStatistics) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.fps, rhs.fps) && messagesPigeonInternal.deepEquals(lhs.cpu, rhs.cpu) && messagesPigeonInternal.deepEquals(lhs.gpu, rhs.gpu) && messagesPigeonInternal.deepEquals(lhs.ram, rhs.ram)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompositionStatistics")
    messagesPigeonInternal.deepHash(value: fps, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: cpu, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: gpu, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: ram, hasher: &hasher)
  }

  public var description: String {
    return "CompositionStatistics(fps: \(String(describing: fps)), cpu: \(String(describing: cpu)), gpu: \(String(describing: gpu)), ram: \(String(describing: ram)))"
  }
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct CompositionStates: Hashable, CustomStringConvertible {
  var recording: Bool
  var streaming: Bool
  var previewing: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompositionStates? {
    let recording = pigeonVar_list[0] as! Bool
    let streaming = pigeonVar_list[1] as! Bool
    let previewing = pigeonVar_list[2] as! Bool

    return CompositionStates(
      recording: recording,
      streaming: streaming,
      previewing: previewing
    )
  }
  func toList() -> [Any?] {
    return [
      recording,
      streaming,
      previewing,
    ]
  }
  static func == (lhs: CompositionStates, rhs: CompositionStates) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.recording, rhs.recording) && messagesPigeonInternal.deepEquals(lhs.streaming, rhs.streaming) && messagesPigeonInternal.deepEquals(lhs.previewing, rhs.previewing)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompositionStates")
    messagesPigeonInternal.deepHash(value: recording, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: streaming, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: previewing, hasher: &hasher)
  }

  public var description: String {
    return "CompositionStates(recording: \(String(describing: recording)), streaming: \(String(describing: streaming)), previewing: \(String(describing: previewing)))"
  }
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated class from Pigeon that represents data sent in messages.
struct AssetTexture: Hashable, CustomStringConvertible {
  var moduleId: String
  var assetId: String
  var textureId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AssetTexture? {
    let moduleId = pigeonVar_list[0] as! String
    let assetId = pigeonVar_list[1] as! String
    let textureId = pigeonVar_list[2] as! Int64

    return AssetTexture(
      moduleId: moduleId,
      assetId: assetId,
      textureId: textureId
    )
  }
  func toList() -> [Any?] {
    return [
      moduleId,
      assetId,
      textureId,
    ]
  }
  static func == (lhs: AssetTexture, rhs: AssetTexture) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return messagesPigeonInternal.deepEquals(lhs.moduleId, rhs.moduleId) && messagesPigeonInternal.deepEquals(lhs.assetId, rhs.assetId) && messagesPigeonInternal.deepEquals(lhs.textureId, rhs.textureId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AssetTexture")
    messagesPigeonInternal.deepHash(value: moduleId, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: assetId, hasher: &hasher)
    messagesPigeonInternal.deepHash(value: textureId, hasher: &hasher)
  }

  public var description: String {
    return "AssetTexture(moduleId: \(String(describing: moduleId)), assetId: \(String(describing: assetId)), textureId: \(String(describing: textureId)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ControlType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AnalogControl(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AnalogSourceControl(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraControl(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FxControl(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LutControl(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlayerControl(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ShaderControl(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SynControl(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ControlBlendMode(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ModuleType(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraPosition(rawValue: enumResultAsInt)
      }
      return nil
    case 141:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraType(rawValue: enumResultAsInt)
      }
      return nil
    case 142:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MessageLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 143:
      return Preview.fromList(self.readValue() as! [Any?])
    case 144:
      return AudioLevel.fromList(self.readValue() as! [Any?])
    case 145:
      return Equalizer.fromList(self.readValue() as! [Any?])
    case 146:
      return Asset.fromList(self.readValue() as! [Any?])
    case 147:
      return Control.fromList(self.readValue() as! [Any?])
    case 148:
      return Composition.fromList(self.readValue() as! [Any?])
    case 149:
      return Module.fromList(self.readValue() as! [Any?])
    case 150:
      return CameraDevice.fromList(self.readValue() as! [Any?])
    case 151:
      return AudioDevice.fromList(self.readValue() as! [Any?])
    case 152:
      return AudioSettings.fromList(self.readValue() as! [Any?])
    case 153:
      return CompositionSettings.fromList(self.readValue() as! [Any?])
    case 154:
      return CompositionStatistics.fromList(self.readValue() as! [Any?])
    case 155:
      return CompositionStates.fromList(self.readValue() as! [Any?])
    case 156:
      return AssetTexture.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ControlType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AnalogControl {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AnalogSourceControl {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraControl {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? FxControl {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? LutControl {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlayerControl {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? ShaderControl {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? SynControl {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? ControlBlendMode {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? ModuleType {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraPosition {
      super.writeByte(140)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraType {
      super.writeByte(141)
      super.writeValue(value.rawValue)
    } else if let value = value as? MessageLevel {
      super.writeByte(142)
      super.writeValue(value.rawValue)
    } else if let value = value as? Preview {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? AudioLevel {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? Equalizer {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? Asset {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? Control {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? Composition {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? Module {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? CameraDevice {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? AudioDevice {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? AudioSettings {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? CompositionSettings {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? CompositionStatistics {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? CompositionStates {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? AssetTexture {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// /////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AestesisEngineApi {
  func newComposition() async throws -> Composition
  func composition() async throws -> Composition
  func updateComposition(composition: Composition) async throws -> Composition
  func settings(settings: CompositionSettings?) async throws -> CompositionSettings
  func updateModule(module: Module) async throws -> Composition
  func addModule(module: Module) async throws -> Composition
  func insertModule(module: Module, index: Int64) async throws -> Composition
  func removeModule(moduleId: String) async throws -> Composition
  func addAssets(moduleId: String, assets: [Asset?]) async throws -> Composition
  func removeAssets(moduleId: String, assetIds: [String?]) async throws -> Composition
  func updateControl(control: Control) throws
  func outputView(show: Bool) throws
  func startRecording(path: String) throws
  func stopRecording() throws
  func cameraDevices() async throws -> [CameraDevice]
  func audioDevices() async throws -> [AudioDevice]
  func openPanel(title: String, directory: String?, multiple: Bool, ext: [String]) async throws -> [String]
  func savePanel(title: String, directory: String?, filename: String, ext: String) async throws -> String?
  func setAssetData(key: String, json: String) throws
  func getAssetData(key: String) throws -> String?
  func setAssetDatas(json: String) throws
  func getAssetDatas() throws -> String?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AestesisEngineApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AestesisEngineApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AestesisEngineApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let newCompositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.newComposition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      newCompositionChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.newComposition()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      newCompositionChannel.setMessageHandler(nil)
    }
    let compositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.composition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compositionChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.composition()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      compositionChannel.setMessageHandler(nil)
    }
    let updateCompositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.updateComposition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateCompositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let compositionArg = args[0] as! Composition
        Task { @MainActor in
          do {
            let result = try await api.updateComposition(composition: compositionArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateCompositionChannel.setMessageHandler(nil)
    }
    let settingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.settings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      settingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg: CompositionSettings? = nilOrValue(args[0])
        Task { @MainActor in
          do {
            let result = try await api.settings(settings: settingsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      settingsChannel.setMessageHandler(nil)
    }
    let updateModuleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.updateModule\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateModuleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let moduleArg = args[0] as! Module
        Task { @MainActor in
          do {
            let result = try await api.updateModule(module: moduleArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateModuleChannel.setMessageHandler(nil)
    }
    let addModuleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.addModule\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addModuleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let moduleArg = args[0] as! Module
        Task { @MainActor in
          do {
            let result = try await api.addModule(module: moduleArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      addModuleChannel.setMessageHandler(nil)
    }
    let insertModuleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.insertModule\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      insertModuleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let moduleArg = args[0] as! Module
        let indexArg = args[1] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.insertModule(module: moduleArg, index: indexArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      insertModuleChannel.setMessageHandler(nil)
    }
    let removeModuleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.removeModule\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeModuleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let moduleIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.removeModule(moduleId: moduleIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeModuleChannel.setMessageHandler(nil)
    }
    let addAssetsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.addAssets\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAssetsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let moduleIdArg = args[0] as! String
        let assetsArg = args[1] as! [Asset?]
        Task { @MainActor in
          do {
            let result = try await api.addAssets(moduleId: moduleIdArg, assets: assetsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      addAssetsChannel.setMessageHandler(nil)
    }
    let removeAssetsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.removeAssets\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAssetsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let moduleIdArg = args[0] as! String
        let assetIdsArg = args[1] as! [String?]
        Task { @MainActor in
          do {
            let result = try await api.removeAssets(moduleId: moduleIdArg, assetIds: assetIdsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeAssetsChannel.setMessageHandler(nil)
    }
    let updateControlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.updateControl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateControlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let controlArg = args[0] as! Control
        do {
          try api.updateControl(control: controlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateControlChannel.setMessageHandler(nil)
    }
    let outputViewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.outputView\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      outputViewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let showArg = args[0] as! Bool
        do {
          try api.outputView(show: showArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      outputViewChannel.setMessageHandler(nil)
    }
    let startRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.startRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRecordingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          try api.startRecording(path: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startRecordingChannel.setMessageHandler(nil)
    }
    let stopRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.stopRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRecordingChannel.setMessageHandler { _, reply in
        do {
          try api.stopRecording()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopRecordingChannel.setMessageHandler(nil)
    }
    let cameraDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.cameraDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cameraDevicesChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.cameraDevices()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      cameraDevicesChannel.setMessageHandler(nil)
    }
    let audioDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.audioDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      audioDevicesChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.audioDevices()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      audioDevicesChannel.setMessageHandler(nil)
    }
    let openPanelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.openPanel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openPanelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        let directoryArg: String? = nilOrValue(args[1])
        let multipleArg = args[2] as! Bool
        let extArg = args[3] as! [String]
        Task { @MainActor in
          do {
            let result = try await api.openPanel(title: titleArg, directory: directoryArg, multiple: multipleArg, ext: extArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      openPanelChannel.setMessageHandler(nil)
    }
    let savePanelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.savePanel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      savePanelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        let directoryArg: String? = nilOrValue(args[1])
        let filenameArg = args[2] as! String
        let extArg = args[3] as! String
        Task { @MainActor in
          do {
            let result = try await api.savePanel(title: titleArg, directory: directoryArg, filename: filenameArg, ext: extArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      savePanelChannel.setMessageHandler(nil)
    }
    let setAssetDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.setAssetData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAssetDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let jsonArg = args[1] as! String
        do {
          try api.setAssetData(key: keyArg, json: jsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAssetDataChannel.setMessageHandler(nil)
    }
    let getAssetDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.getAssetData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAssetDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.getAssetData(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAssetDataChannel.setMessageHandler(nil)
    }
    let setAssetDatasChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.setAssetDatas\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAssetDatasChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jsonArg = args[0] as! String
        do {
          try api.setAssetDatas(json: jsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAssetDatasChannel.setMessageHandler(nil)
    }
    let getAssetDatasChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.aestesis_engine.AestesisEngineApi.getAssetDatas\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAssetDatasChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAssetDatas()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAssetDatasChannel.setMessageHandler(nil)
    }
  }
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MessageAestesisEngineApiProtocol {
  func texture(asset assetArg: AssetTexture) async throws
  func message(level levelArg: MessageLevel, message messageArg: String) async throws
  func preview(preview previewArg: Preview) async throws
  func statistics(statistics statisticsArg: CompositionStatistics) async throws
  func control(control controlArg: Control) async throws
  func audio(level levelArg: AudioLevel) async throws
  func states(states statesArg: CompositionStates) async throws
}
class MessageAestesisEngineApi: MessageAestesisEngineApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func texture(asset assetArg: AssetTexture) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.texture\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([assetArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func message(level levelArg: MessageLevel, message messageArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.message\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([levelArg, messageArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func preview(preview previewArg: Preview) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.preview\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([previewArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func statistics(statistics statisticsArg: CompositionStatistics) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.statistics\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([statisticsArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func control(control controlArg: Control) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.control\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([controlArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func audio(level levelArg: AudioLevel) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.audio\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([levelArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func states(states statesArg: CompositionStates) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.aestesis_engine.MessageAestesisEngineApi.states\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([statesArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
